default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgis
  password: postgis
  pool: 5
  schema_search_path: public

development:
  <<: *default
  database: app_development


test:
  <<: *default
  database: app_test
