default: &default
  adapter: postgresql
  host: db
  username: postgres
  password:
  pool: 5
  schema_search_path: public
  template: template0

development:
  <<: *default
  database: app_development


test:
  <<: *default
  database: app_test
